### ISSUE TITLE
Please help me check the error log

### ISSUE THREAD

**Issue by liketolike** [kuroppoi/entralinked#24]
2023-10-08 23:07:36.676  INFO : Loading configuration ...
2023-10-08 23:07:36.764  INFO : Using configuration Configuration[hostName=local, clearPlayerDreamInfoOnWake=true, allowOverwritingPlayerDreamInfo=false, allowPlayerGameVersionMismatch=false, allowWfcRegistrationThroughLogin=true]
2023-10-08 23:07:36.910  INFO : Loading DLC ...
2023-10-08 23:07:36.933  INFO : Loaded 59 DLC file(s)
2023-10-08 23:07:36.935  INFO : Loading user and profile data ...
2023-10-08 23:07:36.939  INFO : Loading player data ...
2023-10-08 23:07:37.095  INFO : Mapping GameSpy request types ...
2023-10-08 23:07:37.395  INFO : Creating certificate keystore ...
2023-10-08 23:07:37.412  INFO : Cached keystore found - loading it!
2023-10-08 23:07:37.986  INFO : Loading C-Gear and Pokédex skin previews ...
2023-10-08 23:07:38.207  INFO : Cached 57 skin previews
2023-10-08 23:07:38.213  INFO : Starting servers ...
2023-10-08 23:07:38.213  INFO : Starting HTTP server ...
2023-10-08 23:07:38.215  INFO : Starting Javalin ...
2023-10-08 23:07:38.243  INFO : jetty-11.0.15; built: 2023-04-11T18:37:53.775Z; git: 5bc5e562c8d05c5862505aebe5cf83a61bdbcb96; jvm 17.0.8+9-LTS-211
2023-10-08 23:07:38.258 ERROR : Failed to start Javalin
2023-10-08 23:07:38.259 ERROR : Could not start HTTP server
io.javalin.util.JavalinBindException: Port already in use. Make sure no other process is using port 80 and try again.
	at io.javalin.Javalin.start(Javalin.java:182) ~[entralinked.jar:?]
	at entralinked.network.http.HttpServer.start(HttpServer.java:84) [entralinked.jar:?]
	at entralinked.Entralinked.startServers(Entralinked.java:141) [entralinked.jar:?]
	at entralinked.Entralinked.<init>(Entralinked.java:112) [entralinked.jar:?]
	at entralinked.Entralinked.main(Entralinked.java:33) [entralinked.jar:?]
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:80
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402) ~[entralinked.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:398) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[entralinked.jar:?]
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:74) ~[entralinked.jar:?]
	at io.javalin.Javalin.start(Javalin.java:171) ~[entralinked.jar:?]
	... 4 more
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402) ~[entralinked.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:398) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[entralinked.jar:?]
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:74) ~[entralinked.jar:?]
	at io.javalin.Javalin.start(Javalin.java:171) ~[entralinked.jar:?]
	... 4 more
2023-10-08 23:07:38.270  INFO : Stopping servers ...

**Comment by kuroppoi** [comment]
Another program is already using TCP port 80. You'll have to find and close it.

**Comment by liketolike** [comment]
> Another program is already using TCP port 80. You'll have to find and close it.

Thanks,It's working fine!
