### ISSUE TITLE
Error code 20100: WARN : SSL will be disabled because BouncyCastle could not be loaded 

### ISSUE THREAD

**Issue by Awestarz** [kuroppoi/entralinked#38]
I couldn't start Game Sync.
I tried elevating Entralinked through Administrator Command Prompt and it didn't help load bouncycastle.
Entralinked Output:

```
2024-01-18 23:03:10.988 ERROR : Could not add BouncyCastle to SystemClassLoader search
java.nio.file.NoSuchFileException: `libs\bcutil-jdk15on-1.70.jar`
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
	at java.nio.file.Files.copy(Files.java:3160) ~[?:?]
	at entralinked.LauncherAgent.agentmain(LauncherAgent.java:35) ~[entralinked.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491) ~[?:?]
	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:513) ~[?:?]
	at sun.instrument.InstrumentationImpl.loadAgent0(Native Method) ~[?:?]
	at sun.instrument.InstrumentationImpl.loadAgent(InstrumentationImpl.java:556) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at sun.launcher.LauncherHelper.lambda$getMainClassFromJar$0(LauncherHelper.java:576) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at sun.launcher.LauncherHelper.getMainClassFromJar(LauncherHelper.java:571) ~[?:?]
	at sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:778) ~[?:?]
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:686) ~[?:?]
2024-01-18 23:03:11.015  INFO : Loading configuration ...
2024-01-18 23:03:11.054  INFO : No configuration file exists - default configuration will be used
2024-01-18 23:03:11.055 ERROR : Could not load configuration - default configuration will be used
java.io.FileNotFoundException: config.json (Access is denied)
	at java.io.FileOutputStream.open0(Native Method) ~[?:?]
	at java.io.FileOutputStream.open(FileOutputStream.java:293) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
	at com.fasterxml.jackson.core.TokenStreamFactory._fileOutputStream(TokenStreamFactory.java:294) ~[entralinked.jar:?]
	at com.fasterxml.jackson.core.JsonFactory.createGenerator(JsonFactory.java:1428) ~[entralinked.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.createGenerator(ObjectMapper.java:1230) ~[entralinked.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3906) ~[entralinked.jar:?]
	at entralinked.Entralinked.loadConfigFile(Entralinked.java:173) [entralinked.jar:?]
	at entralinked.Entralinked.<init>(Entralinked.java:69) [entralinked.jar:?]
	at entralinked.Entralinked.main(Entralinked.java:33) [entralinked.jar:?]
2024-01-18 23:03:11.058  INFO : Using configuration Configuration[hostName=local, clearPlayerDreamInfoOnWake=true, allowOverwritingPlayerDreamInfo=false, allowPlayerGameVersionMismatch=false, allowWfcRegistrationThroughLogin=true]
2024-01-18 23:03:11.124  INFO : Loading DLC ...
2024-01-18 23:03:11.125  INFO : Extracting default DLC files ...
2024-01-18 23:03:11.128 ERROR : Could not extract default DLC files
java.nio.file.NoSuchFileException: .\dlc\IRAO\CGEAR\01 - Default.bin
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:85) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:236) ~[?:?]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484) ~[?:?]
	at java.nio.file.Files.newOutputStream(Files.java:228) ~[?:?]
	at java.nio.file.Files.copy(Files.java:3160) ~[?:?]
	at entralinked.model.dlc.DlcList.<init>(DlcList.java:48) [entralinked.jar:?]
	at entralinked.Entralinked.<init>(Entralinked.java:94) [entralinked.jar:?]
	at entralinked.Entralinked.main(Entralinked.java:33) [entralinked.jar:?]
2024-01-18 23:03:11.129  INFO : Loading user and profile data ...
2024-01-18 23:03:11.130  INFO : Loading player data ...
2024-01-18 23:03:11.257  INFO : Mapping GameSpy request types ...
2024-01-18 23:03:11.282  WARN : SSL will be disabled because BouncyCastle could not be loaded
2024-01-18 23:03:11.377  INFO : Loading C-Gear and Pokédex skin previews ...
2024-01-18 23:03:11.377  INFO : Cached 0 skin previews
2024-01-18 23:03:11.381  INFO : Starting servers ...
2024-01-18 23:03:11.381  INFO : Starting HTTP server ...
2024-01-18 23:03:11.527  INFO : Staring GameSpy server ...
2024-01-18 23:03:11.612  INFO : GameSpy server listening @ port 29900
2024-01-18 23:03:11.613  INFO : Staring DNS server ...
2024-01-18 23:03:11.627  INFO : DNS server listening @ port 53
2024-01-18 23:03:11.628  INFO : Startup complete! Took a total of 1065 milliseconds
2024-01-18 23:03:11.628  INFO : Configure your DS to use the following DNS server: 192.168.1.165
```

**Comment by kuroppoi** [comment]
The error occurs because the program has no write permissions.
Running it as administrator should generally fix the problem — maybe an antivirus is preventing it from writing to files?

**Comment by Awestarz** [comment]
I got it working, originally I ran the .jar as admin but switched to the .bat and updated my JDK and it works now
