### ISSUE TITLE
Already in bind error still prevails

### ISSUE THREAD

**Issue by pokemonfan6498** [kuroppoi/entralinked#47]
I did everything like in solution to my issue was said but i still get same error even after disabling ICS

**Comment by kuroppoi** [comment]
A program on your PC is already using UDP port 53 and if it's not ICS then I don't know what it is.
You could try running `netstat -aof | findstr :53` in a command prompt to find the process ID of the program that's using it and then kill it using task manager.

**Comment by pokemonfan6498** [comment]
umm im using windows 10

**Comment by pokemonfan6498** [comment]
well i did run and it showed this  
TCP    0.0.0.0:5357           genuine.adobe.com:0    LISTENING       4
  TCP    127.0.0.1:53           genuine.adobe.com:0    LISTENING       4536
  TCP    [::]:5357              DESKTOP-46EMNAI:0      LISTENING       4
  TCP    [::1]:53               DESKTOP-46EMNAI:0      LISTENING       4536
  UDP    0.0.0.0:5353           *:*                                    4712
  UDP    0.0.0.0:5353           *:*                                    2172
  UDP    0.0.0.0:5353           *:*                                    4712
  UDP    0.0.0.0:5355           *:*                                    2172
  UDP    0.0.0.0:53768          *:*                                    2876
  UDP    0.0.0.0:53837          *:*                                    3540
  UDP    127.0.0.1:53           *:*                                    4536
  UDP    [::]:5353              *:*                                    4712
  UDP    [::]:5353              *:*                                    2172
  UDP    [::]:5355              *:*                                    2172
  UDP    [::1]:53               *:*                                    4536

**Comment by kuroppoi** [comment]
The number on the far right is the process ID, so it seems as though process 4536 is what's  hogging the port.
You can find and terminate the process in question at `Task Manager -> Details` or by running the command 
`taskkill /f /pid 4536` in a command prompt.

**Comment by pokemonfan6498** [comment]
it worked but after i rest pc it had diffrent error
2024-03-22 19:38:03.749 ERROR : Could not start DNS server
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:565) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1329) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1299) ~[?:?]
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:133) ~[entralinked.jar:?]
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:130) ~[entralinked.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
	at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:130) ~[entralinked.jar:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:201) ~[entralinked.jar:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:196) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[entralinked.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[entralinked.jar:?]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[entralinked.jar:?]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[entralinked.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[entralinked.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[entralinked.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[entralinked.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[entralinked.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[entralinked.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[entralinked.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[entralinked.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by pokemonfan6498** [comment]
does the program always looks for new port?

**Comment by kuroppoi** [comment]
It does not.
Whatever keeps using port 53 is probably starting automatically every time you turn on your PC, so you'll have to either do something about that or find & kill the process every time.

**Comment by pokemonfan6498** [comment]
You mean kill evey process what has 53 in it?

**Comment by kuroppoi** [comment]
You just follow the instructions again that I gave you earlier.

**Comment by pokemonfan6498** [comment]
I know but every time i boot up the program it creates different dns

**Comment by kuroppoi** [comment]
Weird.
Are you maybe using a VPN?

**Comment by pokemonfan6498** [comment]
No I don't have access to it because it's oaid

**Comment by kuroppoi** [comment]
But does Game Sync work or not?

**Comment by pokemonfan6498** [comment]
I haven't tested yet

**Comment by ketsuban** [comment]
For me `taskkill` didn't help because the PID that was bound to port 53 was an instance of `svchost.exe` which just got restarted when I killed it, so I did some more digging. The culprit turned out to be two Windows services (Host Network Service and Internet Connection Sharing). I disabled those and that got entralinked working.
