### ISSUE TITLE
Could not start DNS server

### ISSUE THREAD

**Issue by Thrilltech** [kuroppoi/entralinked#61]
Hey, first off, I'm using Linux Mint. I have installed OpenJDK-17-JDK Java, and ran the "entralinked.jar" via "sudo java -jar entralinked.jar", with permissions on the whole folder plus the files in it with all permissions for everyone.

So, what the problem here is, is that the "DNS Address is already in use" or something like that, and it therefor stops. I'm gonna post the log here:

2024-06-02 01:44:51.270  INFO : Loading configuration ...
2024-06-02 01:44:51.374  INFO : Using configuration Configuration[hostName=local, clearPlayerDreamInfoOnWake=true, allowOverwritingPlayerDreamInfo=false, allowPlayerGameVersionMismatch=false, allowWfcRegistrationThroughLogin=true]
2024-06-02 01:44:51.533  INFO : Loading DLC ...
2024-06-02 01:44:51.569  INFO : Loaded 59 DLC file(s)
2024-06-02 01:44:51.571  INFO : Loading user and profile data ...
2024-06-02 01:44:51.572  INFO : Loading player data ...
2024-06-02 01:44:51.669  INFO : Mapping GameSpy request types ...
2024-06-02 01:44:52.030  INFO : Creating certificate keystore ...
2024-06-02 01:44:52.054  INFO : Cached keystore found - loading it!
2024-06-02 01:44:52.400  INFO : Loading C-Gear and Pokédex skin previews ...
2024-06-02 01:44:52.651  INFO : Cached 57 skin previews
2024-06-02 01:44:52.657  INFO : Starting servers ...
2024-06-02 01:44:52.658  INFO : Starting HTTP server ...
2024-06-02 01:44:52.906  INFO : Staring GameSpy server ...
2024-06-02 01:44:52.965  INFO : GameSpy server listening @ port 29900
2024-06-02 01:44:52.969  INFO : Staring DNS server ...
2024-06-02 01:44:53.002 ERROR : Could not start DNS server
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: The Address is already in use
2024-06-02 01:44:53.004  INFO : Stopping servers ...
2024-06-02 01:44:53.005  INFO : Stopping HTTP server ...
2024-06-02 01:44:53.027  INFO : Stopping GameSpy server ...
2024-06-02 01:44:55.043  INFO : GameSpy server stopped

Pls help if possible, I have no knowledge in Java nor DNS whatsoever. I don't even really understand what DNS is for. But that shouldn't matter  as long as I know how to use it as shown in tutorials. Anyways, please help me.

**Comment by Mowstyl** [comment]
I think it's caused by systemd-resolve service. I have the same problem on an ubuntu server.

**Comment by Pinkietron** [comment]
I get the same issue on windows 10:

2024-06-22 18:59:02.347  INFO : Loading configuration ...
2024-06-22 18:59:02.457  INFO : Using configuration Configuration[hostName=local, clearPlayerDreamInfoOnWake=true, allowOverwritingPlayerDreamInfo=false, allowPlayerGameVersionMismatch=false, allowWfcRegistrationThroughLogin=true]
2024-06-22 18:59:02.553  INFO : Loading DLC ...
2024-06-22 18:59:02.598  INFO : Loaded 59 DLC file(s)
2024-06-22 18:59:02.601  INFO : Loading user and profile data ...
2024-06-22 18:59:02.605  INFO : Loading player data ...
2024-06-22 18:59:02.806  INFO : Mapping GameSpy request types ...
2024-06-22 18:59:03.212  INFO : Creating certificate keystore ...
2024-06-22 18:59:03.235  INFO : Cached keystore found - loading it!
2024-06-22 18:59:03.640  INFO : Loading C-Gear and Pokédex skin previews ...
2024-06-22 18:59:04.023  INFO : Cached 57 skin previews
2024-06-22 18:59:04.032  INFO : Starting servers ...
2024-06-22 18:59:04.033  INFO : Starting HTTP server ...
2024-06-22 18:59:04.396  INFO : Staring GameSpy server ...
2024-06-22 18:59:04.555  INFO : GameSpy server listening @ port 29900
2024-06-22 18:59:04.557  INFO : Staring DNS server ...
2024-06-22 18:59:04.580 ERROR : Could not start DNS server
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164) ~[?:?]
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:133) ~[entralinked.jar:?]
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:130) ~[entralinked.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?]
	at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:130) ~[entralinked.jar:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:201) ~[entralinked.jar:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:196) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[entralinked.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[entralinked.jar:?]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[entralinked.jar:?]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[entralinked.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[entralinked.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[entralinked.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[entralinked.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[entralinked.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[entralinked.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[entralinked.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[entralinked.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
2024-06-22 18:59:04.588  INFO : Stopping servers ...
2024-06-22 18:59:04.601  INFO : Stopping HTTP server ...
2024-06-22 18:59:04.623  INFO : Stopping GameSpy server ...
2024-06-22 18:59:06.734  INFO : GameSpy server stopped

**Comment by Thrilltech** [comment]
> I think it's caused by systemd-resolve service. I have the same problem on an ubuntu server.

Thanks, though what does that even mean? And do you know gow to fix it?

**Comment by Mowstyl** [comment]
> > I think it's caused by systemd-resolve service. I have the same problem on an ubuntu server.
> 
> Thanks, though what does that even mean? And do you know gow to fix it?

To solve it, use `sudo systemctl stop systemd-resolve`. Then you can start entralinked. After you've finished working with it, use `sudo systemctl start systemd-resolve`. Keep in mind that systemd-resolve may be needed by other programs to work.



> I get the same issue on windows 10:
> 
> 2024-06-22 18:59:02.347 INFO : Loading configuration ... 2024-06-22 18:59:02.457 INFO : Using configuration Configuration[hostName=local, clearPlayerDreamInfoOnWake=true, allowOverwritingPlayerDreamInfo=false, allowPlayerGameVersionMismatch=false, allowWfcRegistrationThroughLogin=true] 2024-06-22 18:59:02.553 INFO : Loading DLC ... 2024-06-22 18:59:02.598 INFO : Loaded 59 DLC file(s) 2024-06-22 18:59:02.601 INFO : Loading user and profile data ... 2024-06-22 18:59:02.605 INFO : Loading player data ... 2024-06-22 18:59:02.806 INFO : Mapping GameSpy request types ... 2024-06-22 18:59:03.212 INFO : Creating certificate keystore ... 2024-06-22 18:59:03.235 INFO : Cached keystore found - loading it! 2024-06-22 18:59:03.640 INFO : Loading C-Gear and Pokédex skin previews ... 2024-06-22 18:59:04.023 INFO : Cached 57 skin previews 2024-06-22 18:59:04.032 INFO : Starting servers ... 2024-06-22 18:59:04.033 INFO : Starting HTTP server ... 2024-06-22 18:59:04.396 INFO : Staring GameSpy server ... 2024-06-22 18:59:04.555 INFO : GameSpy server listening @ port 29900 2024-06-22 18:59:04.557 INFO : Staring DNS server ... 2024-06-22 18:59:04.580 ERROR : Could not start DNS server java.net.BindException: Address already in use: bind at sun.nio.ch.Net.bind0(Native Method) ~[?:?] at sun.nio.ch.Net.bind(Net.java:555) ~[?:?] at sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1194) ~[?:?] at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1164) ~[?:?] at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:133) ~[entralinked.jar:?] at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:130) ~[entralinked.jar:?] at java.security.AccessController.doPrivileged(AccessController.java:569) ~[?:?] at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:130) ~[entralinked.jar:?] at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:201) ~[entralinked.jar:?] at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:196) ~[entralinked.jar:?] at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[entralinked.jar:?] at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[entralinked.jar:?] at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[entralinked.jar:?] at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[entralinked.jar:?] at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[entralinked.jar:?] at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[entralinked.jar:?] at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[entralinked.jar:?] at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[entralinked.jar:?] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[entralinked.jar:?] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[entralinked.jar:?] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[entralinked.jar:?] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[entralinked.jar:?] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[entralinked.jar:?] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[entralinked.jar:?] at java.lang.Thread.run(Thread.java:833) ~[?:?] 2024-06-22 18:59:04.588 INFO : Stopping servers ... 2024-06-22 18:59:04.601 INFO : Stopping HTTP server ... 2024-06-22 18:59:04.623 INFO : Stopping GameSpy server ... 2024-06-22 18:59:06.734 INFO : GameSpy server stopped

Another Windows service is using port 53 (DNS port). According to a guy from the Microsoft technical support forum, that service is related to Hyper-V (virtualization stuff). To fix it, open cmd with administrator privileges and run the following commands BEFORE opening entralinked.
`sc stop hns
sc stop sharedaccess`
Entralinked should start without errors if both commands work. After it has finished loading, run `sc start hns`. Said service can run even if you are using port 53, so there shouldn't be any problems.

I hope this helps.

**Comment by Pinkietron** [comment]
> Another Windows service is using port 53 (DNS port). According to a guy from the Microsoft technical support forum, that service is related to Hyper-V (virtualization stuff). To fix it, open cmd with administrator privileges and run the following commands BEFORE opening entralinked. `sc stop hns` `sc stop sharedaccess` Entralinked should start without errors if both commands work. After it has finished loading, run `sc start hns` (with admin privileges). Said service can run even if you are using port 53, so there shouldn't be any problems.
> 
> I hope this helps.

I tried the last bit for windows and entralinked would not start properly, throwing the same error, and I made sure to enter the commands _before_ launching it
