### ISSUE TITLE
ERROR CODE: 13209

### ISSUE THREAD

**Issue by thadK7** [kuroppoi/entralinked#66]
I successfully created a game sync ID for pokemon black, but when I try to use the Unova link for black 2 it keeps giving me this error when I input my game sync ID.
Entralinked highlighted this in red
2024-08-03 15:02:29.926 ERROR : Caught exception
java.lang.NullPointerException: Cannot invoke "entralinked.GameVersion.isVersion2()" because the return value of "entralinked.model.player.Player.getGameVersion()" is null
	at entralinked.network.http.pgl.PglHandler.handleMemoryLink(PglHandler.java:359) ~[entralinked.jar:?]
	at entralinked.network.http.pgl.PglHandler.handlePglGetRequest(PglHandler.java:137) ~[entralinked.jar:?]
	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19) ~[entralinked.jar:?]
	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:38) ~[entralinked.jar:?]
	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88) ~[entralinked.jar:?]
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53) ~[entralinked.jar:?]
	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41) ~[entralinked.jar:?]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) ~[entralinked.jar:?]
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) ~[entralinked.jar:?]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) ~[entralinked.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[entralinked.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[entralinked.jar:?]
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:57) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[entralinked.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[entralinked.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[entralinked.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[entralinked.jar:?]
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558) ~[entralinked.jar:?]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379) ~[entralinked.jar:?]
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146) ~[entralinked.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[entralinked.jar:?]
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411) [entralinked.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969) [entralinked.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194) [entralinked.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149) [entralinked.jar:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]

**Comment by kuroppoi** [comment]
Yeah it's a bug with the current release. You have to use Game Sync to tuck in a Pokémon on your Black game before using Memory Link.

**Comment by thadK7** [comment]
Thank you, that finally got it to work.
