### ISSUE TITLE
Could not start DNS server - Port 29900 | Windows 11

### ISSUE THREAD

**Issue by Angelofthenight091** [kuroppoi/entralinked#74]
Running Windows 11, latest updates. 
When I attempt to Run the application I cant start the DNS Server and provides the error of port 29900.

I checked the firewall and nothing is blocking it.  Turned off the firewall to test. Same issues.
Unable to figure out how to resolve this issue. 

2024-10-10 22:10:51.469  INFO : Loading configuration ...
2024-10-10 22:10:51.477  INFO : No configuration file exists - default configuration will be used
2024-10-10 22:10:51.541  INFO : Using configuration Configuration[hostName=local, clearPlayerDreamInfoOnWake=true, allowOverwritingPlayerDreamInfo=false, allowPlayerGameVersionMismatch=false, allowWfcRegistrationThroughLogin=true]
2024-10-10 22:10:51.663  INFO : Loading DLC ...
2024-10-10 22:10:51.666  INFO : Extracting default DLC files ...
2024-10-10 22:10:51.818  INFO : Loaded 59 DLC file(s)
2024-10-10 22:10:51.820  INFO : Loading user and profile data ...
2024-10-10 22:10:51.823  INFO : Loading player data ...
2024-10-10 22:10:52.003  INFO : Mapping GameSpy request types ...
2024-10-10 22:10:52.387  INFO : Creating certificate keystore ...
2024-10-10 22:10:52.403  INFO : No keystore found - generating one!
2024-10-10 22:10:52.844  INFO : Loading C-Gear and Pokédex skin previews ...
2024-10-10 22:10:53.296  INFO : Cached 57 skin previews
2024-10-10 22:10:53.302  INFO : Starting servers ...
2024-10-10 22:10:53.303  INFO : Starting HTTP server ...
2024-10-10 22:10:53.750  INFO : Staring GameSpy server ...
2024-10-10 22:10:53.821  INFO : GameSpy server listening @ port 29900
2024-10-10 22:10:53.822  INFO : Staring DNS server ...
2024-10-10 22:10:53.838 ERROR : Could not start DNS server
java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:565) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1329) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1299) ~[?:?]
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:133) ~[entralinked.jar:?]
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:130) ~[entralinked.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
	at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:130) ~[entralinked.jar:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:201) ~[entralinked.jar:?]
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:196) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[entralinked.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491) ~[entralinked.jar:?]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973) ~[entralinked.jar:?]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260) ~[entralinked.jar:?]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356) ~[entralinked.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[entralinked.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[entralinked.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[entralinked.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[entralinked.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[entralinked.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[entralinked.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[entralinked.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
2024-10-10 22:10:53.850  INFO : Stopping servers ...
2024-10-10 22:10:53.859  INFO : Stopping HTTP server ...
2024-10-10 22:10:53.871  INFO : Stopping GameSpy server ...
2024-10-10 22:10:55.943  INFO : GameSpy server stopped

**Comment by Angelofthenight091** [comment]
I attempted this on a Windows 10 system latest updates. no issues what so ever. 
However, my main rig is Windows 11.. and would prefer to use it.

**Comment by kuroppoi** [comment]
Firewall is not the issue. Please read the [troubleshooting guide.](https://github.com/kuroppoi/entralinked/wiki/Troubleshooting#address-already-in-use-bind)
