### ISSUE TITLE
stopped running when trying to open in chromebook

### ISSUE THREAD

**Issue by POKEMONMASTER944** [kuroppoi/entralinked#75]
worked fine then this

2024-10-24 08:13:57.054  INFO : Loading configuration ...
2024-10-24 08:13:57.673  INFO : Using configuration Configuration[hostName=local, clearPlayerDreamInfoOnWake=true, allowOverwritingPlayerDreamInfo=false, allowPlayerGameVersionMismatch=false, allowWfcRegistrationThroughLogin=true]
2024-10-24 08:13:57.907  WARN : No local host candidate could be found - loopback address will be used
2024-10-24 08:13:57.926  INFO : Loading DLC ...
2024-10-24 08:13:58.056  INFO : Loaded 59 DLC file(s)
2024-10-24 08:13:58.087  INFO : Loading user and profile data ...
2024-10-24 08:13:58.124  INFO : Loading player data ...
2024-10-24 08:13:58.430  INFO : Mapping GameSpy request types ...
2024-10-24 08:13:59.659  INFO : Creating certificate keystore ...
2024-10-24 08:13:59.735  INFO : Cached keystore found - loading it!
2024-10-24 08:14:00.690  INFO : Loading C-Gear and Pokédex skin previews ...
2024-10-24 08:14:01.474  INFO : Cached 57 skin previews
2024-10-24 08:14:01.500  INFO : Starting servers ...
2024-10-24 08:14:01.522  INFO : Starting HTTP server ...
2024-10-24 08:14:01.986 ERROR : Could not start HTTP server
io.javalin.util.JavalinException: MultiException[java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:80, java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:443]
	at io.javalin.Javalin.start(Javalin.java:186) ~[entralinked.jar:?]
	at entralinked.network.http.HttpServer.start(HttpServer.java:87) [entralinked.jar:?]
	at entralinked.Entralinked.startServers(Entralinked.java:140) [entralinked.jar:?]
	at entralinked.Entralinked.<init>(Entralinked.java:112) [entralinked.jar:?]
	at entralinked.Entralinked.main(Entralinked.java:33) [entralinked.jar:?]
Caused by: org.eclipse.jetty.util.MultiException: Multiple exceptions
	at org.eclipse.jetty.util.MultiException.ifExceptionThrow(MultiException.java:117) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:410) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[entralinked.jar:?]
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:74) ~[entralinked.jar:?]
	at io.javalin.Javalin.start(Javalin.java:171) ~[entralinked.jar:?]
	... 4 more
	Suppressed: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:443
		at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[entralinked.jar:?]
		at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304) ~[entralinked.jar:?]
		at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402) ~[entralinked.jar:?]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
		at org.eclipse.jetty.server.Server.doStart(Server.java:398) ~[entralinked.jar:?]
		at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[entralinked.jar:?]
		at io.javalin.jetty.JettyServer.start(JettyServer.kt:74) ~[entralinked.jar:?]
		at io.javalin.Javalin.start(Javalin.java:171) ~[entralinked.jar:?]
		at entralinked.network.http.HttpServer.start(HttpServer.java:87) [entralinked.jar:?]
		at entralinked.Entralinked.startServers(Entralinked.java:140) [entralinked.jar:?]
		at entralinked.Entralinked.<init>(Entralinked.java:112) [entralinked.jar:?]
		at entralinked.Entralinked.main(Entralinked.java:33) [entralinked.jar:?]
	Caused by: java.net.BindException: Permission denied
		at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
		at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
		at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
		at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
		at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339) ~[entralinked.jar:?]
		... 20 more
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:80
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:344) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402) ~[entralinked.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:398) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[entralinked.jar:?]
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:74) ~[entralinked.jar:?]
	at io.javalin.Javalin.start(Javalin.java:171) ~[entralinked.jar:?]
	... 4 more
Caused by: java.net.BindException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:555) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337) ~[?:?]
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294) ~[?:?]
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:339) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:304) ~[entralinked.jar:?]
	at org.eclipse.jetty.server.Server.lambda$doStart$0(Server.java:402) ~[entralinked.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:398) ~[entralinked.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[entralinked.jar:?]
	at io.javalin.jetty.JettyServer.start(JettyServer.kt:74) ~[entralinked.jar:?]
	at io.javalin.Javalin.start(Javalin.java:171) ~[entralinked.jar:?]
	... 4 more
2024-10-24 08:14:02.091  INFO : Stopping servers ...

**Comment by kuroppoi** [comment]
Ports 80 and 443 are probably privileged ports, but I have no idea. ChromeOS is weird, good luck.
